### ISSUE TITLE
Doesn't pass the PouchDB test suite in Node using sqlite3

### ISSUE THREAD

**Issue by nolanlawson** [calvinmetcalf/SQLdown#25]
I know I'm just piling on now, @calvinmetcalf... :wink:  But I couldn't contain my curiosity, so I tested in Node.js as well.

Steps to repro:

```
hub clone pouchdb/pouchdb
cd pouchdb
npm install sqldown sqlite3
LEVEL_ADAPTER=sqldown npm run test-node
```

Error:

```
    ✓ Calling db.changes({since: 'latest'}) 
Unhandled rejection Error: The genericPool is not initialized.
    at Pool_SQLite3.Pool.release (/Users/nolan/workspace/pouchdb/node_modules/sqldown/node_modules/knex/lib/pool.js:66:14)
    at /Users/nolan/workspace/pouchdb/node_modules/sqldown/node_modules/knex/lib/client.js:45:10
    at tryCatcher (/Users/nolan/workspace/pouchdb/node_modules/sqldown/node_modules/bluebird/js/main/util.js:24:31)
    at Promise._resolveFromResolver (/Users/nolan/workspace/pouchdb/node_modules/sqldown/node_modules/bluebird/js/main/promise.js:427:31)
    at new Promise (/Users/nolan/workspace/pouchdb/node_modules/sqldown/node_modules/bluebird/js/main/promise.js:53:37)
    at Client_SQLite3.Client.releaseConnection (/Users/nolan/workspace/pouchdb/node_modules/sqldown/node_modules/knex/lib/client.js:44:10)
    at Runner_SQLite3.<anonymous> (/Users/nolan/workspace/pouchdb/node_modules/sqldown/node_modules/knex/lib/runner.js:245:24)
    at Runner_SQLite3.tryCatcher (/Users/nolan/workspace/pouchdb/node_modules/sqldown/node_modules/bluebird/js/main/util.js:24:31)
    at Runner_SQLite3.cleanupConnection (/Users/nolan/workspace/pouchdb/node_modules/sqldown/node_modules/bluebird/js/main/method.js:15:34)
    at Object.finallyHandler (/Users/nolan/workspace/pouchdb/node_modules/sqldown/node_modules/bluebird/js/main/finally.js:39:31)
    at Object.tryCatcher (/Users/nolan/workspace/pouchdb/node_modules/sqldown/node_modules/bluebird/js/main/util.js:24:31)
    at Promise._settlePromiseFromHandler (/Users/nolan/workspace/pouchdb/node_modules/sqldown/node_modules/bluebird/js/main/promise.js:454:31)
    at Promise._settlePromiseAt (/Users/nolan/workspace/pouchdb/node_modules/sqldown/node_modules/bluebird/js/main/promise.js:530:18)
    at Async._drainQueue (/Users/nolan/workspace/pouchdb/node_modules/sqldown/node_modules/bluebird/js/main/async.js:182:12)
    at Async._drainQueues (/Users/nolan/workspace/pouchdb/node_modules/sqldown/node_modules/bluebird/js/main/async.js:187:10)
    at Async.drainQueues (/Users/nolan/workspace/pouchdb/node_modules/sqldown/node_modules/bluebird/js/main/async.js:15:14)
    at process._tickCallback (node.js:442:13)
```

BTW I recently updated the [PouchDB for LevelDOWN authors](https://gist.github.com/nolanlawson/f2f4d7e2e6f426502b94) if you want to take a look. Nothing you weren't already aware of, though.

**Comment by calvinmetcalf** [comment]
but wait additional issues: [this line](https://github.com/pouchdb/pouchdb/blob/master/lib/setup.js#L29) prevents using postgres or mysql adapters

**Comment by nolanlawson** [comment]
@calvinmetcalf Does that happen even if you use the `LEVEL_PREFIX` option? Kinda surprised, because I'm pretty sure I got this working in riak with `riak://`-style URLs.
